// Telugu Movie Dataset - array of movie objects
const movies = [
  { id: 1,  title: "Baahubali 2: The Conclusion", genre: "Action",    rating: 8.2, year: 2017, image: "assets/images/baahubali-2-the-conclusion.jpg" },
  { id: 2,  title: "Eega",                        genre: "Fantasy",   rating: 7.9, year: 2012, image: "assets/images/eega.jpg" },
  { id: 3,  title: "Ala Vaikunthapurramuloo",     genre: "Action",    rating: 7.3, year: 2020, image: "assets/images/ala-vaikunthapurramuloo.jpg" },
  { id: 4,  title: "Arjun Reddy",                 genre: "Romance",   rating: 7.8, year: 2017, image: "assets/images/arjun-reddy.jpg" },
  { id: 5,  title: "RRR",                         genre: "Action",    rating: 8.0, year: 2022, image: "assets/images/rrr.jpg" },
  { id: 6,  title: "Pushpa: The Rise",            genre: "Action",    rating: 7.6, year: 2021, image: "assets/images/pushpa-the-rise.jpg" },
  { id: 7,  title: "Jersey",                      genre: "Drama",     rating: 8.0, year: 2019, image: "assets/images/jersey.jpg" },
  { id: 8,  title: "Mahanati",                    genre: "Drama",     rating: 8.4, year: 2018, image: "assets/images/mahanati.jpg" },
  { id: 9,  title: "C/o Kancharapalem",           genre: "Romance",   rating: 8.2, year: 2018, image: "assets/images/co-kancharapalem.jpg" },
  { id: 10, title: "Rangasthalam",                genre: "Action",    rating: 7.8, year: 2018, image: "assets/images/rangasthalam.jpg" },
  { id: 11, title: "Sita Ramam",                  genre: "Romance",   rating: 8.1, year: 2022, image: "assets/images/sita-ramam.jpg" },
  { id: 12, title: "Baahubali: The Beginning",    genre: "Action",    rating: 8.0, year: 2015, image: "assets/images/baahubali-the-beginning.jpg" },
  { id: 13, title: "Pellichoopulu",               genre: "Romance",   rating: 7.9, year: 2016, image: "assets/images/pellichoopulu.jpg" },
  { id: 14, title: "Fidaa",                       genre: "Romance",   rating: 7.3, year: 2017, image: "assets/images/fidaa.jpg" },
  { id: 15, title: "Maharshi",                    genre: "Drama",     rating: 6.8, year: 2019, image: "assets/images/maharshi.jpg" },
  { id: 16, title: "Sarileru Neekevvaru",         genre: "Action",    rating: 6.5, year: 2020, image: "assets/images/sarileru-neekevvaru.jpg" },
  { id: 17, title: "Bheemla Nayak",               genre: "Action",    rating: 6.7, year: 2022, image: "assets/images/bheemla-nayak.jpg" },
  { id: 18, title: "DJ: Duvvada Jagannadham",     genre: "Action",    rating: 5.8, year: 2017, image: "assets/images/dj-duvvada-jagannadham.jpg" },
  { id: 19, title: "Geetha Govindam",             genre: "Romance",   rating: 7.2, year: 2018, image: "assets/images/geetha-govindam.jpg" },
  { id: 20, title: "Ante Sundaraniki",            genre: "Comedy",    rating: 7.5, year: 2022, image: "assets/images/ante-sundaraniki.jpg" },
  { id: 21, title: "Kanche",                      genre: "Drama",     rating: 7.6, year: 2015, image: "assets/images/kanche.jpg" },
  { id: 22, title: "Kshanam",                     genre: "Thriller",  rating: 7.9, year: 2016, image: "assets/images/kshanam.jpg" },
  { id: 23, title: "Ghazi",                       genre: "Action",    rating: 7.6, year: 2017, image: "assets/images/ghazi.jpg" },
  { id: 24, title: "Awe!",                        genre: "Thriller",  rating: 7.3, year: 2018, image: "assets/images/awe.jpg" },
  { id: 25, title: "Agent Sai Srinivasa Athreya", genre: "Comedy",    rating: 7.8, year: 2019, image: "assets/images/agent-sai-srinivasa-athreya.jpg" },
  { id: 26, title: "Oh! Baby",                    genre: "Comedy",    rating: 7.5, year: 2019, image: "assets/images/oh-baby.jpg" },
  { id: 27, title: "Evaru",                       genre: "Thriller",  rating: 7.8, year: 2019, image: "assets/images/evaru.jpg" },
  { id: 28, title: "HIT: The First Case",         genre: "Thriller",  rating: 7.4, year: 2020, image: "assets/images/hit-the-first-case.jpg" },
  { id: 29, title: "Colour Photo",                genre: "Romance",   rating: 7.8, year: 2020, image: "assets/images/colour-photo.jpg" },
  { id: 30, title: "Jathi Ratnalu",               genre: "Comedy",    rating: 7.2, year: 2021, image: "assets/images/jathi-ratnalu.jpg" },
  { id: 31, title: "Uppena",                      genre: "Romance",   rating: 6.8, year: 2021, image: "assets/images/uppena.jpg" },
  { id: 32, title: "Love Story",                  genre: "Romance",   rating: 7.0, year: 2021, image: "assets/images/love-story.jpg" },
  { id: 33, title: "Shyam Singha Roy",            genre: "Drama",     rating: 7.1, year: 2021, image: "assets/images/shyam-singha-roy.jpg" },
  { id: 34, title: "Bimbisara",                   genre: "Fantasy",   rating: 6.9, year: 2022, image: "assets/images/bimbisara.jpg" },
  { id: 35, title: "Karthikeya 2",                genre: "Action",    rating: 7.0, year: 2022, image: "assets/images/karthikeya-2.jpg" },
  { id: 36, title: "Major",                       genre: "Drama",     rating: 8.0, year: 2022, image: "assets/images/major.jpg" },
  { id: 37, title: "Pushpa 2: The Rule",          genre: "Action",    rating: 7.4, year: 2024, image: "assets/images/pushpa-2-the-rule.jpg" },
  { id: 38, title: "Kalki 2898 AD",               genre: "Sci-Fi",    rating: 6.8, year: 2024, image: "assets/images/kalki-2898-ad.jpg" },
  { id: 39, title: "Hi Nanna",                    genre: "Romance",   rating: 7.5, year: 2023, image: "assets/images/hi-nanna.jpg" },
  { id: 40, title: "Dasara",                      genre: "Action",    rating: 6.5, year: 2023, image: "assets/images/dasara.jpg" },
  { id: 41, title: "Virupaksha",                  genre: "Thriller",  rating: 7.2, year: 2023, image: "assets/images/virupaksha.jpg" },
  { id: 42, title: "Baby",                        genre: "Comedy",    rating: 7.6, year: 2023, image: "assets/images/baby.jpg" },
  { id: 43, title: "Mangalavaaram",               genre: "Thriller",  rating: 7.5, year: 2023, image: "assets/images/mangalavaaram.jpg" },
  { id: 44, title: "Miss Shetty Mr Polishetty",   genre: "Comedy",    rating: 6.5, year: 2023, image: "assets/images/miss-shetty-mr-polishetty.jpg" },
  { id: 45, title: "Bhola Shankar",               genre: "Action",    rating: 4.5, year: 2023, image: "assets/images/bhola-shankar.jpg" },
  { id: 46, title: "Adipurush",                   genre: "Action",    rating: 4.8, year: 2023, image: "assets/images/adipurush.jpg" },
  { id: 47, title: "Gandeevadhari Arjuna",        genre: "Action",    rating: 5.2, year: 2023, image: "assets/images/gandeevadhari-arjuna.jpg" },
  { id: 48, title: "Skanda",                      genre: "Action",    rating: 5.0, year: 2023, image: "assets/images/skanda.jpg" },
  { id: 49, title: "Jailer (Telugu)",              genre: "Action",    rating: 7.3, year: 2023, image: "assets/images/jailer.jpg" },
  { id: 50, title: "Salaar",                      genre: "Action",    rating: 6.4, year: 2023, image: "assets/images/salaar.jpg" },
];

module.exports = movies;
