const db = require('./database');

const movies = [
  { id: 1,  title: "Baahubali 2: The Conclusion", genre: "Action",   rating: 8.2, year: 2017, image: "assets/images/baahubali-2-the-conclusion.jpg", synopsis: "The epic conclusion to the Baahubali saga where Mahendra Baahubali fights to reclaim his throne and honor against his ruthless uncle and mother." },
  { id: 2,  title: "Eega",                       genre: "Fantasy",   rating: 7.9, year: 2012, image: "assets/images/eega.jpg", synopsis: "After a young man is killed by a powerful industrialist, he returns as a tiny fly to seek revenge and protect his beloved, in this imaginative and thrilling tale." },
  { id: 3,  title: "Ala Vaikunthapurramuloo",    genre: "Action",    rating: 7.3, year: 2020, image: "assets/images/ala-vaikunthapurramuloo.jpg", synopsis: "A wealthy man returns home and faces family conflicts while trying to win back his lost love in this entertaining romantic action film." },
  { id: 4,  title: "Arjun Reddy",                genre: "Romance",   rating: 7.8, year: 2017, image: "assets/images/arjun-reddy.jpg", synopsis: "A talented surgeon struggles with personal turmoil and reunites with his lost love, exploring themes of redemption and second chances." },
  { id: 5,  title: "RRR",                        genre: "Action",    rating: 8.0, year: 2022, image: "assets/images/rrr.jpg", synopsis: "Two freedom fighters from different nations unite against a common enemy in this high-octane action extravaganza set during the British Raj." },
  { id: 6,  title: "Pushpa: The Rise",           genre: "Action",    rating: 7.6, year: 2021, image: "assets/images/pushpa-the-rise.jpg", synopsis: "A small-time smuggler rises to become a formidable power in the red sanders black market, facing police and rival gangs along the way." },
  { id: 7,  title: "Jersey",                     genre: "Drama",     rating: 8.0, year: 2019, image: "assets/images/jersey.jpg", synopsis: "A former cricketer makes a comeback at an unusual age to prove his worth and win the love of his family in this emotional sports drama." },
  { id: 8,  title: "Mahanati",                   genre: "Drama",     rating: 8.4, year: 2018, image: "assets/images/mahanati.jpg", synopsis: "A biopic celebrating the legendary life and career of one of Telugu cinema's greatest actresses and her timeless contributions." },
  { id: 9,  title: "C/o Kancharapalem",          genre: "Romance",   rating: 8.2, year: 2018, image: "assets/images/co-kancharapalem.jpg", synopsis: "Four elderly people in a small town find unexpected companionship and love as they navigate life's twilight years with humor and grace." },
  { id: 10, title: "Rangasthalam",               genre: "Action",    rating: 7.8, year: 2018, image: "assets/images/rangasthalam.jpg", synopsis: "A deaf man from a small village protects his community and seeks justice against powerful feudal lords in this gripping revenge drama." },
  { id: 11, title: "Sita Ramam",                 genre: "Romance",   rating: 8.1, year: 2022, image: "assets/images/sita-ramam.jpg", synopsis: "An army officer stumbles upon the letters of a woman he has never met and embarks on a journey to discover an unexpected love story." },
  { id: 12, title: "Baahubali: The Beginning",   genre: "Action",    rating: 8.0, year: 2015, image: "assets/images/baahubali-the-beginning.jpg", synopsis: "The origin story of the legendary warrior Baahubali unfolds as he discovers his true identity and prepares for an epic battle for the throne." },
  { id: 13, title: "Pellichoopulu",              genre: "Romance",   rating: 7.9, year: 2016, image: "assets/images/pellichoopulu.jpg", synopsis: "A young couple challenges traditional marriage customs and societal expectations to forge their own path toward a modern relationship." },
  { id: 14, title: "Fidaa",                      genre: "Romance",   rating: 7.3, year: 2017, image: "assets/images/fidaa.jpg", synopsis: "A runaway bride and a young man from a village fall in love, but their differences threaten to keep them apart in this romantic comedy drama." },
  { id: 15, title: "Maharshi",                   genre: "Drama",     rating: 6.8, year: 2019, image: "assets/images/maharshi.jpg", synopsis: "A successful entrepreneur reconsiders his life choices and returns to his roots, exploring themes of purpose, privilege, and social responsibility." },
  { id: 16, title: "Sarileru Neekevvaru",        genre: "Action",    rating: 6.5, year: 2020, image: "assets/images/sarileru-neekevvaru.jpg", synopsis: "A soldier returns home on leave and romances a girl while navigating family pressures and unexpected conflicts in this romantic action thriller." },
  { id: 17, title: "Bheemla Nayak",              genre: "Action",    rating: 6.7, year: 2022, image: "assets/images/bheemla-nayak.jpg", synopsis: "A police officer and a reformed criminal clash in a small village, leading to explosive confrontations and surprising revelations about justice." },
  { id: 18, title: "DJ: Duvvada Jagannadham",    genre: "Action",    rating: 5.8, year: 2017, image: "assets/images/dj-duvvada-jagannadham.jpg", synopsis: "A cook with a dark past becomes entangled in dangerous situations and organized crime while protecting those he cares about most." },
  { id: 19, title: "Geetha Govindam",            genre: "Romance",   rating: 7.2, year: 2018, image: "assets/images/geetha-govindam.jpg", synopsis: "A conservative girl meets a free-spirited boy and they navigate the complexities of modern love in this lighthearted romantic film." },
  { id: 20, title: "Ante Sundaraniki",           genre: "Comedy",    rating: 7.5, year: 2022, image: "assets/images/ante-sundaraniki.jpg", synopsis: "A young couple from different religious backgrounds must overcome their families' objections and societal prejudices to be together." },
  { id: 21, title: "Kanche",                     genre: "Drama",     rating: 7.6, year: 2015, image: "assets/images/kanche.jpg", synopsis: "A World War II love story between an Indian soldier and a nurse unfolds amid the horrors of war, testing their bond and sacrifices." },
  { id: 22, title: "Kshanam",                    genre: "Thriller",  rating: 7.9, year: 2016, image: "assets/images/kshanam.jpg", synopsis: "A mysterious girl changes a man's life within a single moment, leading to a fast-paced thriller filled with unexpected twists and revelations." },
  { id: 23, title: "Ghazi",                      genre: "Action",    rating: 7.6, year: 2017, image: "assets/images/ghazi.jpg", synopsis: "Indian Navy commandos undertake a covert rescue mission during wartime, balancing courage, duty, and personal sacrifices in this action thriller." },
  { id: 24, title: "Awe!",                       genre: "Thriller",  rating: 7.3, year: 2018, image: "assets/images/awe.jpg", synopsis: "Five interconnected strangers in a city find themselves entangled in a suspenseful thriller where their fates are mysteriously intertwined." },
  { id: 25, title: "Agent Sai Srinivasa Athreya", genre: "Comedy",  rating: 7.8, year: 2019, image: "assets/images/agent-sai-srinivasa-athreya.jpg", synopsis: "A brilliant detective tackles mysterious cases in his small town with wit and humor, unveiling surprising secrets and solving puzzles." },
  { id: 26, title: "Oh! Baby",                   genre: "Comedy",    rating: 7.5, year: 2019, image: "assets/images/oh-baby.jpg", synopsis: "A grandmother magically transforms into a young woman and rediscovers her zest for life, romance, and adventure in this heartwarming film." },
  { id: 27, title: "Evaru",                      genre: "Thriller",  rating: 7.8, year: 2019, image: "assets/images/evaru.jpg", synopsis: "A cop's personal vendetta leads to a twisted game of cat and mouse with a mysterious criminal, blurring the lines between justice and revenge." },
  { id: 28, title: "HIT: The First Case",        genre: "Thriller",  rating: 7.4, year: 2020, image: "assets/images/hit-the-first-case.jpg", synopsis: "A determined detective investigates a baffling missing person case that leads him down a dark path of corruption and hidden crimes." },
  { id: 29, title: "Colour Photo",               genre: "Romance",   rating: 7.8, year: 2020, image: "assets/images/colour-photo.jpg", synopsis: "A couple's love story unfolds through photographs and memories, exploring how colors and moments can capture the essence of a relationship." },
  { id: 30, title: "Jathi Ratnalu",              genre: "Comedy",    rating: 7.2, year: 2021, image: "assets/images/jathi-ratnalu.jpg", synopsis: "Three misfit friends get into hilarious situations and misadventures as they navigate life, friendship, and unexpected romance in modern times." },
  { id: 31, title: "Uppena",                     genre: "Romance",   rating: 6.8, year: 2021, image: "assets/images/uppena.jpg", synopsis: "A fisherman's son falls for a landlord's daughter, leading to a tragic love story that challenges class boundaries and social conventions." },
  { id: 32, title: "Love Story",                 genre: "Romance",   rating: 7.0, year: 2021, image: "assets/images/love-story.jpg", synopsis: "A privileged girl and a working-class boy find themselves falling deeply for each other despite the vast economic and social differences between them." },
  { id: 33, title: "Shyam Singha Roy",           genre: "Drama",     rating: 7.1, year: 2021, image: "assets/images/shyam-singha-roy.jpg", synopsis: "A writer enters a magical time portal and discovers the tragic love story and unfinished business of a legendary freedom fighter from the past." },
  { id: 34, title: "Bimbisara",                  genre: "Fantasy",   rating: 6.9, year: 2022, image: "assets/images/bimbisara.jpg", synopsis: "An ancient warrior magically appears in the modern world, blending mythology and contemporary life in this imaginative fantasy adventure." },
  { id: 35, title: "Karthikeya 2",               genre: "Action",    rating: 7.0, year: 2022, image: "assets/images/karthikeya-2.jpg", synopsis: "An adventurer embarks on a quest to unravel ancient secrets and uncover the truth behind mysterious historical artifacts across different continents." },
  { id: 36, title: "Major",                      genre: "Drama",     rating: 8.0, year: 2022, image: "assets/images/major.jpg", synopsis: "The inspiring true story of an Indian military officer's heroic contribution to national security and his sacrifice for his country's defense." },
  { id: 37, title: "Pushpa 2: The Rule",         genre: "Action",    rating: 7.4, year: 2024, image: "assets/images/pushpa-2-the-rule.jpg", synopsis: "Pushpa consolidates his criminal empire and faces new challenges as rivals and authorities close in from all sides in this action-packed sequel." },
  { id: 38, title: "Kalki 2898 AD",              genre: "Sci-Fi",    rating: 6.8, year: 2024, image: "assets/images/kalki-2898-ad.jpg", synopsis: "A futuristic epic blends ancient mythology with cutting-edge science fiction, following a warrior destined to save humanity in a dystopian world." },
  { id: 39, title: "Hi Nanna",                   genre: "Romance",   rating: 7.5, year: 2023, image: "assets/images/hi-nanna.jpg", synopsis: "A widowed single father and a young woman form an unexpected connection, exploring themes of family, love, and finding happiness again." },
  { id: 40, title: "Dasara",                     genre: "Action",    rating: 6.5, year: 2023, image: "assets/images/dasara.jpg", synopsis: "A man from a poor background becomes entangled with powerful criminals, leading to violence and a desperate fight for redemption and freedom." },
  { id: 41, title: "Virupaksha",                 genre: "Thriller",  rating: 7.2, year: 2023, image: "assets/images/virupaksha.jpg", synopsis: "A woman discovers her husband's shocking double life, leading to a thrilling investigation into deception, crime, and dark family secrets." },
  { id: 42, title: "Baby",                       genre: "Comedy",    rating: 7.6, year: 2023, image: "assets/images/baby.jpg", synopsis: "A young woman's accidental pregnancy leads to a series of misadventures and comedic situations as she navigates motherhood and relationships." },
  { id: 43, title: "Mangalavaaram",              genre: "Thriller",  rating: 7.5, year: 2023, image: "assets/images/mangalavaaram.jpg", synopsis: "A mysterious killer targets women on Wednesdays, and a determined officer races against time to uncover the killer's identity and motives." },
  { id: 44, title: "Miss Shetty Mr Polishetty",  genre: "Comedy",    rating: 6.5, year: 2023, image: "assets/images/miss-shetty-mr-polishetty.jpg", synopsis: "A successful career woman and a police officer from different worlds collide, leading to hilarious misunderstandings and unexpected romance." },
  { id: 45, title: "Bhola Shankar",              genre: "Action",    rating: 4.5, year: 2023, image: "assets/images/bhola-shankar.jpg", synopsis: "A man seeks revenge against those who wronged his family, embarking on a violent revenge spree that tests his morals and relationships." },
  { id: 46, title: "Adipurush",                  genre: "Action",    rating: 4.8, year: 2023, image: "assets/images/adipurush.jpg", synopsis: "An ambitious retelling of the Ramayana epic, blending ancient mythology with modern filmmaking to bring the timeless tale to contemporary audiences." },
  { id: 47, title: "Gandeevadhari Arjuna",       genre: "Action",    rating: 5.2, year: 2023, image: "assets/images/gandeevadhari-arjuna.jpg", synopsis: "An archer with mystical powers must use his skills to protect his loved ones from dangerous enemies and restore justice in a corrupt world." },
  { id: 48, title: "Skanda",                     genre: "Action",    rating: 5.0, year: 2023, image: "assets/images/skanda.jpg", synopsis: "A young warrior protects his village from invaders while uncovering his extraordinary heritage and destiny in this mythological action adventure." },
  { id: 49, title: "Jailer (Telugu)",            genre: "Action",    rating: 7.3, year: 2023, image: "assets/images/jailer.jpg", synopsis: "A prison jailer's life transforms when his daughter enters his world, leading to emotional conflicts and unexpected confrontations with powerful criminals." },
  { id: 50, title: "Salaar",                     genre: "Action",    rating: 6.4, year: 2023, image: "assets/images/salaar.jpg", synopsis: "Two childhood friends find themselves on opposite sides of a gang war, leading to explosive confrontations and personal sacrifices in this action thriller." },
];

// Seed the database
db.db.serialize(() => {
  db.init();
  db.seedMovies(movies);
  
  db.db.close((err) => {
    if (err) {
      console.error('Error closing database:', err);
      process.exit(1);
    } else {
      console.log('✓ Database connection closed. Seeding complete!');
      process.exit(0);
    }
  });
});
